//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaAnimalia.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string dog_max_score_m_1 {
            get {
                return ((string)(this["dog_max_score_m_1"]));
            }
            set {
                this["dog_max_score_m_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string bear_max_score_m_1 {
            get {
                return ((string)(this["bear_max_score_m_1"]));
            }
            set {
                this["bear_max_score_m_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string giraffe_max_score_m_1 {
            get {
                return ((string)(this["giraffe_max_score_m_1"]));
            }
            set {
                this["giraffe_max_score_m_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string dog_max_score_l_1 {
            get {
                return ((string)(this["dog_max_score_l_1"]));
            }
            set {
                this["dog_max_score_l_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string bear_max_score_l_1 {
            get {
                return ((string)(this["bear_max_score_l_1"]));
            }
            set {
                this["bear_max_score_l_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string giraffe_max_score_l_1 {
            get {
                return ((string)(this["giraffe_max_score_l_1"]));
            }
            set {
                this["giraffe_max_score_l_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string bear_max_score_a_1 {
            get {
                return ((string)(this["bear_max_score_a_1"]));
            }
            set {
                this["bear_max_score_a_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string bear_max_score_p_1 {
            get {
                return ((string)(this["bear_max_score_p_1"]));
            }
            set {
                this["bear_max_score_p_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string dog_max_score_a_1 {
            get {
                return ((string)(this["dog_max_score_a_1"]));
            }
            set {
                this["dog_max_score_a_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string dog_max_score_p_1 {
            get {
                return ((string)(this["dog_max_score_p_1"]));
            }
            set {
                this["dog_max_score_p_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string giraffe_max_score_a_1 {
            get {
                return ((string)(this["giraffe_max_score_a_1"]));
            }
            set {
                this["giraffe_max_score_a_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string giraffe_max_score_p_1 {
            get {
                return ((string)(this["giraffe_max_score_p_1"]));
            }
            set {
                this["giraffe_max_score_p_1"] = value;
            }
        }
    }
}
